### PR TITLE
Don't include window and group in Query.

### LINKED ISSUE #11: `Query` options can be used in inappropriate places.
Currently, `Client::find` and `Client::search` both accept a `Query` which has fields for filters, grouping, and windowing. But `find` and `search` only accept filters and windowing. I've got WIP implementations of `list` and `findadd`, the former only takes filters and grouping, the later only filters.

There are at least a couple of solutions:
- the most straightforward is to simply split up `Query` into its component parts and only accept the parts that are valid for each command.
- it'd also be possible to do something with phantom-types, but this seems more complicated for no gain.

### PR DESCRIPTION
**Pull request by tomprince**
Fixes #11.

I'm not sure if the window stuff works; I don't have mpd 0.20 here. 

I wonder if there is some clever way to handle the version differences and only expose supported options?

### CODE REVIEW

**Comment by tomprince** [comment]
Ping. (Note [here](https://github.com/kstep/rust-mpd/pull/14/files?w=1) are the changes ignoring whitespace).

**Comment by tomprince** [comment]
Ping.

**Comment by kstep** [comment]
Why not use `Range` type for windowing?

**Comment by tomprince** [comment]
That would probably make sense. I was just factoring out the existing parameters into separate ones. I also only have mpd 0.19 here, which doesn't have support for windowing, so I'm not able to test it. My inclination would be to leave it as is, and then incrementally improve it later.

**Comment by kstep** [comment]
Added #19 as a reminder for enhancement.

**Pull request merged**
