### PR TITLE
Add a basic test of sticker functionality.

### PR DESCRIPTION
**Pull request by tomprince**
This is about the simplest test you can imagine, but it also starts to add some infrastructure for testing mpd with realistic data (rather than just running some commands and printing their output).

### CODE REVIEW

**Comment by tomprince** [comment]
It looks like the version of mpd on travis is too old to support stickers.

**Comment by kstep** [comment]
That's awesome job! Thank you very much!
Once test turns green, I'll merge it.

**Comment by tomprince** [comment]
I think this is ready to merge.

**Comment by tomprince** [comment]
I did hide it intentionally:
- The `Sticker` type isn't currently used publicly. It just exists to abstract out parsing the `sticker_name=sticker_value` format that mpd returns stickers in.
- Even if `Sticker` was used publicly, I'd be inclined to keep the module private and just expose the type.

**Comment by kstep** [comment]
It just came to my mind: it would be nice to provide stickers as `HashMap<String, String>` for users.

**Comment by tomprince** [comment]
Yeah, that was one of the considerations I had when I didn't make the `sticker` module public.

**Pull request merged**
